import * as React from 'react';
import { TabContentWrapper } from '../shared/TabContentWrapper';

interface ContentTabProps {
    content: string | null;
}

export const ContentTab: React.FC<ContentTabProps> = ({ content }) => {
    return (
        <TabContentWrapper
            title="Learning Content"
            description="Here is the content generated by the Content Agent for the current module. Review this material before proceeding to the assessment."
        >
            {content ? (
                <div className="prose prose-invert max-w-none bg-gray-800/50 p-6 rounded-lg border border-gray-700">
                    <pre className="whitespace-pre-wrap font-sans">{content}</pre>
                </div>
            ) : (
                <div className="text-gray-500 text-center p-8 border-2 border-dashed border-gray-700 rounded-lg">
                    Learning content for the selected module will appear here.
                </div>
            )}
        </TabContentWrapper>
    );
};